"""Pandera schema classes for Matrix Project."""
from typing import Optional

import pandera.polars as pa
from pandera.typing import Series

# THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.


class MatrixNodeSchema(pa.DataFrameModel):
    """Schema for matrixnode TSV file."""
    
    
    
    
    
    id: Series[str]
    
    
    
    
    
    
    
    
    category: Series[str]
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    


class MatrixEdgeSchema(pa.DataFrameModel):
    """Schema for matrixedge TSV file."""
    
    
    
    
    
    subject: Series[str]
    
    
    
    
    
    predicate: Series[str]
    
    
    
    
    
    object: Series[str]
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    


class UnionedNodeSchema(pa.DataFrameModel):
    """Schema for unionednode TSV file."""
    


class UnionedEdgeSchema(pa.DataFrameModel):
    """Schema for unionededge TSV file."""
    
    
    


class MatrixEdgeListSchema(pa.DataFrameModel):
    """Schema for matrixedgelist TSV file."""
    
    
    
    
    
    edges: Optional[Series[str]] = pa.Field(nullable=True)
    
    


class MatrixNodeListSchema(pa.DataFrameModel):
    """Schema for matrixnodelist TSV file."""
    
    
    
    
    
    nodes: Optional[Series[str]] = pa.Field(nullable=True)
    
    

