---
name: Create Release Artifacts

on:
  release:
    types: [created]

# Add permissions needed to upload to releases
permissions:
  contents: write

jobs:
  create-artifacts:
    name: Create and Upload Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create artifact directory
        run: mkdir -p artifacts

      - name: Copy valid edge type table to artifacts
        run: cp src/matrix_schema/schema/valid_biolink_edge_types.tsv artifacts/
          
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          
      - name: Upload as workflow artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: valid-biolink-edge-types
          path: artifacts
