---
name: Create Release Artifacts

on:
  release:
    types: [created]

jobs:
  create-artifacts:
    name: Create and Upload Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create artifact directory
        run: mkdir -p artifacts

      - name: Copy valid edge type table to artifacts
        run: cp src/matrix_schema/schema/valid_biolink_edge_types.tsv artifacts/

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/valid_biolink_edge_types.tsv
          
      - name: Upload as workflow artifact (for debugging)
        uses: actions/upload-artifact@v3
        with:
          name: valid-biolink-edge-types
          path: src/matrix_schema/schema/valid_biolink_edge_types.tsv